# Generated by Django 2.0.7 on 2018-07-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_dosimetry', '0002_result_measurement_period_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personneldosimetryusers',
            name='clinics',
            field=models.ManyToManyField(to='personnel_dosimetry.Clinic'),
        ),
    ]
