# Generated by Django 2.0.7 on 2018-07-09 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel_dosimetry', '0002_result_measurement_period_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosimeterLaterality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosimeter_laterality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotReturnedDosimeters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
            ],
            options={
                'ordering': ['personnel', 'report'],
            },
        ),
        migrations.AddField(
            model_name='profession',
            name='landauer_profession_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='dosimeter_type',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel_dosimetry.Profession'),
        ),
        migrations.AlterField(
            model_name='personneldosimetryusers',
            name='clinics',
            field=models.ManyToManyField(to='personnel_dosimetry.Clinic'),
        ),
        migrations.AlterField(
            model_name='vendordosimeterplacement',
            name='dosimeter_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel_dosimetry.DosimeterPlacement'),
        ),
        migrations.AddField(
            model_name='notreturneddosimeters',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel_dosimetry.Personnel'),
        ),
        migrations.AddField(
            model_name='vendordosimeterplacement',
            name='dosimeter_laterality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel_dosimetry.DosimeterLaterality'),
        ),
    ]
