# Generated by Django 2.0.5 on 2018-07-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
            ],
            options={
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name', 'hospital'],
            },
        ),
        migrations.CreateModel(
            name='ClinicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DirtyClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirty_name', models.TextField()),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluoro_times.Clinic')),
            ],
            options={
                'ordering': ['clinic', 'dirty_name'],
            },
        ),
        migrations.CreateModel(
            name='DirtyModality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirty_name', models.TextField()),
            ],
            options={
                'ordering': ['dirty_name'],
            },
        ),
        migrations.CreateModel(
            name='DirtyOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirty_name', models.TextField()),
            ],
            options={
                'ordering': ['operator', 'dirty_name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_no', models.TextField()),
                ('exam_date', models.DateTimeField()),
                ('fluoro_time', models.FloatField()),
                ('dose', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('dirty_clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fluoro_times.DirtyClinic')),
                ('dirty_modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fluoro_times.DirtyModality')),
                ('dirty_operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fluoro_times.DirtyOperator')),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pediatric', models.BooleanField(default=False)),
                ('anatomy_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluoro_times.AnatomyRegion')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dose_unit', models.CharField(choices=[('gm', 'Gym2'), ('gdm', 'Gydm2'), ('gcm', 'Gycm2'), ('dgm', 'dGym2'), ('dgdm', 'dGydm2'), ('dgcm', 'dGycm2'), ('cgm', 'cGym2'), ('cgdm', 'cGydm2'), ('cgcm', 'cGycm2')], max_length=4, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModalityClinicMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluoro_times.Clinic')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluoro_times.Modality')),
            ],
            options={
                'ordering': ['clinic', 'modality'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluoro_times.Clinic')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OperatorClinicMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluoro_times.Clinic')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluoro_times.Operator')),
            ],
            options={
                'ordering': ['clinic', 'operator'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluoro_times.ExamDescription'),
        ),
        migrations.AddField(
            model_name='dirtyoperator',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluoro_times.Operator'),
        ),
        migrations.AddField(
            model_name='dirtymodality',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluoro_times.Modality'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluoro_times.ClinicCategory'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fluoro_times.Hospital'),
        ),
    ]
