# Generated by Django 2.0.7 on 2018-07-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
            ],
            options={
                'get_latest_by': 'datum',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('host_identifier', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ris_name', models.TextField()),
                ('body_part', models.TextField()),
                ('technique', models.TextField()),
                ('kv', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mas', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('filter_cu', models.DecimalField(decimal_places=1, max_digits=2)),
                ('focus', models.IntegerField()),
                ('grid', models.IntegerField(null=True)),
                ('diamond_view', models.TextField()),
                ('edge_filter_kernel_size', models.IntegerField()),
                ('edge_filter_gain', models.DecimalField(decimal_places=2, max_digits=4)),
                ('harmonization_kernel_size', models.IntegerField()),
                ('harmonization_gain', models.DecimalField(decimal_places=2, max_digits=4)),
                ('noise_reduction', models.BooleanField()),
                ('image_auto_amplification', models.BooleanField()),
                ('image_amplification_gain', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('sensitivity', models.IntegerField()),
                ('lut', models.TextField()),
                ('datum', models.DateTimeField()),
                ('history', models.ManyToManyField(to='skeleton_protocols.Protocol')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton_protocols.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='backup',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton_protocols.Machine'),
        ),
        migrations.AddField(
            model_name='backup',
            name='protocol',
            field=models.ManyToManyField(to='skeleton_protocols.Protocol'),
        ),
    ]
