# Generated by Django 2.0.7 on 2018-07-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('host_identifier', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ris_name', models.TextField()),
                ('body_part', models.TextField()),
                ('technique', models.TextField()),
                ('kv', models.IntegerField()),
                ('mas', models.DecimalField(decimal_places=2, max_digits=3)),
                ('filter_cu', models.DecimalField(decimal_places=2, max_digits=3)),
                ('focus', models.IntegerField()),
                ('diamond_view', models.TextField()),
                ('edge_filter_kernel_size', models.IntegerField()),
                ('edge_filter_gain', models.DecimalField(decimal_places=2, max_digits=3)),
                ('harmonization_kernel_size', models.IntegerField()),
                ('harmonization_gain', models.DecimalField(decimal_places=2, max_digits=3)),
                ('noise_reduction', models.TextField()),
                ('image_auto_amplification', models.TextField()),
                ('image_amplification_gain', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('sensitivity', models.IntegerField()),
                ('lut', models.TextField()),
                ('last_modification', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton_protocols.Machine')),
            ],
        ),
    ]
